### ISSUE TITLE
Pushing the transit button gives the hiking route!

### ISSUE THREAD

**Issue by jidanni** [mapsme/omim#10821]
1. Download app from Google Play
2. Try a route from A to B
3. At the top of the screen there are about 5 circular buttons, tap the trolley car one
3. At the bottom of the screen a hiker image will appear, along with hiking route.
4. Now press the hiking/walking button. Some other route appears, but it is not hiking.

**Comment by jidanni** [comment]
![Screenshot_20190502-022808-270x480](https://user-images.githubusercontent.com/1230959/57056224-94b06c00-6cd3-11e9-9f6e-1b4a092b1cbd.jpg)

**Comment by jidanni** [comment]
OK, perhaps it is the "walking part of a public transportation solution".
But then why does pressing the hiking/walking button give a much longer solution as seen in.#10823?

**Comment by zsoltsandor** [comment]
Searching for public transport in Budapest gives a "too long walk" error.
The app is in Hungarian, but still. Budapest has valid GTFS data.[
![Screenshot_20190502-172043](https://user-images.githubusercontent.com/4585996/57086632-cab71580-6cfe-11e9-91a3-316afa4c115f.png)

**Comment by gmoryes** [comment]
> Searching for public transport in Budapest gives a "too long walk" error.
> The app is in Hungarian, but still. Budapest has valid GTFS data.[
> ![Screenshot_20190502-172043](https://user-images.githubusercontent.com/4585996/57086632-cab71580-6cfe-11e9-91a3-316afa4c115f.png)

Hello! Update your maps to the latest version please, the problem should be fixed.

**Comment by gmoryes** [comment]
> OK, perhaps it is the "walking part of a public transportation solution".
> But then why does pressing the hiking/walking button give a much longer solution as seen in.#10823?
> (Locations all near 24.1816,120.8662.)

This is really strange, we will explore this problem, thank you!

**Comment by zsoltsandor** [comment]
> Hello! Update your maps to the latest version please, the problem should be fixed.

Hi, I did, even deleted the installed map and reinstalled it, and I still have the same error, both in the branded 
(from Play) and the unbranded (from F-Droid) version. Thus I still have to rely on other services, like Here and Yandex, for a Google-free commute.

**Comment by zsoltsandor** [comment]
My problem has been fixed, thumbs up guys!

**Comment by jidanni** [comment]
OK I also get a sensible walking route too now.
