### ISSUE TITLE
Android build errors

### ISSUE THREAD

**Issue by dew54** [mapsme/omim#12072]
Hi guys, i'm trying to compile the android app but i have the following errors:

`  /home/dev/omim/android/jni/com/mapswithme/maps/PrivateVariables.cpp:159:30: error: use of undeclared identifier 'BOOKMARKS_SUBSCRIPTION_SIGHTS_SERVER_ID'
      return env->NewStringUTF(BOOKMARKS_SUBSCRIPTION_SIGHTS_SERVER_ID);
                               ^
  /home/dev/omim/android/jni/com/mapswithme/maps/PrivateVariables.cpp:166:30: error: use of undeclared identifier 'BOOKMARKS_SUBSCRIPTION_SIGHTS_YEARLY_PRODUCT_ID'
      return env->NewStringUTF(BOOKMARKS_SUBSCRIPTION_SIGHTS_YEARLY_PRODUCT_ID);
                               ^
  /home/dev/omim/android/jni/com/mapswithme/maps/PrivateVariables.cpp:173:30: error: use of undeclared identifier 'BOOKMARKS_SUBSCRIPTION_SIGHTS_MONTHLY_PRODUCT_ID'
      return env->NewStringUTF(BOOKMARKS_SUBSCRIPTION_SIGHTS_MONTHLY_PRODUCT_ID);
                               ^
  /home/dev/omim/android/jni/com/mapswithme/maps/PrivateVariables.cpp:179:38: error: use of undeclared identifier 'BOOKMARKS_SUBSCRIPTION_SIGHTS_NOT_USED_LIST'
      std::vector<std::string> items = BOOKMARKS_SUBSCRIPTION_SIGHTS_NOT_USED_LIST;
`

I'm looking everywhere but i can't find the fix, please, could you help me?
Thanks a lot, Davide

**Comment by kconger** [comment]
I'm getting the same issue, a few months back I was able to build it fine.

**Comment by alexzatsepin** [comment]
Hi @dew54 ,

Thank you for your report. The compilation error is fixed in this PR https://github.com/mapsme/omim/pull/12096 . Update the master please and let us know if you have any problems.

**Comment by dew54** [comment]
Hello @alexzatsepin , i've updated the project but the problem persists.. I've found a turn around defining those variables in `private.h`, the build success but when i run the app and it asks me to download the map the app crashes.. 
Please, any suggestion?
Thx, davide

**Comment by alexzatsepin** [comment]
Hi @dew54 ! 

Did you run /omim/configure.sh script before building the project? That script should substitute all needed parameters in your private.h, you should just choose "open source mode" in console during script launch.

**Comment by dew54** [comment]
Hi @alexzatsepin ,first,  thanks for your quick reply!
Yes i've updated with command `git pull origin master `, then i've run `./configure.sh` and tried to rebuild again, same problem.. i've added your suggested edits manually and ran again ./configure.sh but nothing changes.
Maybe i'm doing something wrong with git.. Please, let me know.
Thx, Davide
PS: I've got no choice when i run `./configure.sh`, it does everything by itself.

**Comment by kconger** [comment]
I can confirm it resolved the issue for me.
