### ISSUE TITLE
POI list language is set to keyboard language

### ISSUE THREAD

**Issue by fqdb** [mapsme/omim#3974]
I sometimes use Google Pinyin keyboard, but when this keyboard is active, the options in the POI list are in Chinese. (at least, that's what seems to be causing this, I tried changing system language and clearing app data)

Maybe this was done intentionally, but it completely foregoes the possibility that a user using a different keyboard is not fully proficient in that language. Besides, several keyboards, such as Swiftkey and Google Pinyin are multilingual. Please add an option to set the POI list language manually.

For completeness, I'm using a Huawes P7-L10 running Android 5.1 and Maps.Me version 6.2.5-Google.

Video: https://gfycat.com/PaltryShockingBaiji

**Comment by Zverik** [comment]
This must have been fixed in the new release due to be published in a week or so. Please test the "Beta" build from http://osmz.ru/mwm/

**Comment by fqdb** [comment]
The issue is still present in the beta (Beta: 2016-08-06 04:00)

**Comment by fqdb** [comment]
https://github.com/mapsme/omim/issues/3448

**Comment by mxa** [comment]
This issue is still present. I can't add POIs in another language. Please fix.

**Comment by mxa** [comment]
Duplicate of https://github.com/mapsme/omim/issues/3448

**Comment by matkoniecz** [comment]
Yes, it is still present.

**Comment by mxa** [comment]
This bug is still there.

**Comment by mxa** [comment]
https://nibblestew.blogspot.de/2018/03/stop-trying-to-guess-display-language.html
