### ISSUE TITLE
Do NOT follow current location

### ISSUE THREAD

**Issue by thany** [mapsme/omim#4334]
In an earlier version, the compass button in the lower right used to have three states:
follow location, follow location & direction, don't follow

Now, it has two states:
follow location, follow location & direction

It's not possible to make the app NOT follow my current location. Yes, one can pan to another location and it won't jump back. But at any random moment while simply using the app, it might jump back to whatever my current location is. Also, when switching to another app, and then back to maps.me, it will always jump back to the current location. Should. Not. Happen. Ever.

This destroys the use-case of preparing for a holiday, meaning a lot of back-and-forth between browser and maps.me, looking for points of interest to bookmark. This becomes completely frustrating.

Please put back the three-state compass button. And make the app ALWAYS remember the state of that button.

**Comment by thany** [comment]
Any chance of a fix?

**Comment by thany** [comment]
Seriously, any chance of a fix?!

**Comment by thany** [comment]
Again, let's kick this issue.

Here's another scenario:
I'm on the train. Out the window, I see something interesting. Let's call it a church. I want to mark it on the map, so I quickly grab my phone and fire up maps.me. I pan over to that church to bookmark it. But then! Suddenly! The map pans back to my current location! Which is easily a few kilometres farther since I noticed the church - I'm on a high-speed train after all. Now, I'm no longer able to find that church.

Do you see why it's important to have a very explicit "do not follow my current location" mode?

Making it implicit the way it is currently, doesn't solve the problem - it only introduces these bugs:
1) The map may pan back to my current location out of the blue
2) The map _always_ pans back to my current location after switching from another app back to maps.me.

This is why the app must have an explicit switch NOT to follow the user's current location _at all_.

Please, PLEASE have this fixed. I CANNOT use the app like this.

**Comment by Alexuser1** [comment]
Hello Thany!

Please answer to a same questions (by map pans back to current position):
1) Your location is defined by GPS or WiFi/3G lan?
2) At momemt you want to mark object, "My position" button was such a blue arrow or crosshair?
This information need to understanding app stage at it moment.

Why it's important:
1) If location defined not by GPS (satellites) then it defined by base stations. In this case location defines by irregular jumps from previous base station to next. And if we at "in position" ("My position" button below zoom buttons similar blue arrow) when location data is updated the map scrolls to current location.
2) If in this case we not in position ("My position" button as crosshair) then scroll of the map should not be

Thank you!
Alexander

**Comment by thany** [comment]
1) GPS
2) Not a blue arrow

I don't understand why this is so hard. It's just a matter of having the location button as a tristate button: follow location, follow location + compass, don't follow.

Maps.me used to have this around version 6.0, but was removed. And I've been complaining ever since, because it's greatly annoying.

Why is it so hard to revert back to the way it was? You don't even have to design anything.

**Comment by burivuh** [comment]
This state was too confusing for a huge number of users, so no, we will not revert it back.

**Comment by thany** [comment]
Oh come on. You know that's bollocks. It's perfectly fine.

**Comment by thany** [comment]
Well, you're just making it harder on yourselves. All you need to do is add a way to NOT follow the user's location, and a tristate location button is by *considerable* margin the most UX-friendly way to achieve it. Now you've put yourselves up for a completely unnecessary challenge to make it more obscure and easier to understand at the same time.

Seriously, having removed this function is so mind bogglingly naive in the first place. Now you're unwilling to make it work sanely ever again? My gogly goodness you need to learn a lot.

Enough rantinf though.

What would *you* propose then? Got a better idea??

**Comment by burivuh** [comment]
Thank you for your helpful UX insights.
But still our plan is to fix bugs and to make alert behavior less intrusive.

Currently, these are considered as bugs:

1) In some cases firing geolocation alerts after switching Android activities inside application.
2) In some cases ignoring a user scrolling actions on the map before deciding to switch map to a "Follow position" mode instead of "Not in position".
3) In some cases ignoring previous "My Position" control state on a relatively warm start.

**Comment by redmanmale** [comment]
Why don't you move that behavior in settings? And disable that option (DO NOT FOLLOW current location) by default?
Than most users wouldn't be _confused_ and those who really need this option could get what they want.

**Comment by thany** [comment]
Until you need to switch it over quickly when you're on the train and an interesting POI zips by, and you want to figure out what it is by checking the map.

That what the tristate button was absolutely perfect for.

I don't think that a tristate button will cause confusion. Seriously. The trick is to design it well. A traffic light is also a tristate indicator, and that works beautifully, for absolutely everyone to understand.

**Comment by thany** [comment]
In the current latest version, it still "flies back home" when starting the app, which happens probably when the app hasn't been used for an arbitrary amount of time.

I never gave it permission to do that. I expect the app to remember where it left off, and also remember the fact that I panned away from my current location, which effectively disables following the current location.

Not having that at unpredictable times is greatly unproductive. This. Has. To. Be. Fixed.

I said it before and I will say it again: TRISTATE BUTTON

**Comment by thany** [comment]
Also let me just emphasize how embarrassing this issue is getting. I have to downgrade to version 6.0 in order for this problem not to occur. That means it's been around since version 6.1-ish. That means this issue has existed easily for a couple of months! Why?

**Comment by thany** [comment]
The location button is now remembered.

So when I move away from my current location, the button becomes a darts target, and stays that way.

BUT, if the app is closed for X amount of time and started again, it happily flies back to my current position.

Please fix this. Arbitrary timeouts are bad.

**Comment by thany** [comment]
For Pete's sake guys, would you fix this damn issue already?! How long does an issue have to remain open for you guys to apply a 10 minute fix for it?

**Comment by thany** [comment]
Tristate button.

DONE.

**Comment by thany** [comment]
Incredible. Still no fix. Care to explain why? This is a shitty issue, occurs EVERY the I start the app. Fully reproducible. Why is this not getting fixed??

The fix is a simple one as well.

Yes, this is me being annoyed. After 5 months and no replies, can you blame me?

**Comment by stevegdavis** [comment]
@thany I agree the tristate button is the best option, I have managed to put the "don't follow" option back (just 1 line of code) on my own branch of the repro, not sure if you can build the app yourself to achieve this?

**Comment by thany** [comment]
Still no fix. Care to explain why? This is a shitty issue, occurs EVERY the I start the app. Fully reproducible. Why is this not getting fixed??

@stevegdavis Thanks for figuring out it's just one bloody line of code. Goes to show how unwilling the devs are. Unbelievable.

**Comment by stevegdavis** [comment]
@thany As they said it is a deliberate change not a bug as such, but I agree having the ability to tri-state the button was a good feature (something osmand doesn't have), after I made the changes to my repo I found that the button has 4 states probably because of don't follow and don't follow/or locate but it is a minor irritation but it would take more work to get it to work correctly that's probably why they are reluctant to do so.

**Comment by thany** [comment]
Reluctant or not, it's a bug, and a regression at that. It used to work fine (SEVEN MONTHS AGO, devs!) and now it works horribly. Frankly, I don't care if it's intended like this - it just means the intention isclearly wrong. By design means bad design.

Either way, this has to be fixed.

**Comment by thany** [comment]
Fix this issue please. It's annoying.

**Comment by jacko9000** [comment]
I completely agree with thany on this issue.

Furthermore, when the app first starts after installation, why are location services even needed at all?  Can't I just browse a map of the world without reference to my current location (which I spoof anyway)?

I tried version 6.0.7 which thany mentioned, and it's a good talking point, as it doesn't ask for location services to be enabled upon startup after installation.  This is correct.  What is incorrect, is that when the geolocation button is then pressed, the "Please enable Location services" dialog is not displayed, but should be.  *THIS* is the point where this dialog should be displayed, *NOT* upon startup after installation.  If the user then opts to display the location settings from this dialog then, upon resuming MAPS.ME, the app should check if location services were indeed enabled by the user and, if so, switch the geolocation button on; otherwise, off.  Similar logic should be followed when the "Share My Location" menu command is chosen.

It is unreasonable for MAPS.ME to expect users to enable location services for no reason.  If it must prompt users to enable location services, then it should do so at the correct time (i.e. when location services are actually required).

**Comment by thany** [comment]
That's not precisely the issue, bit closely related. 

I may not want it to follow current location even with GPS enabled/active. Simply because I'm working on a part of the maps that isn't "here".

Please just reimplement the bloody tristate button. It's a five minute fix, for Pete's sake!!!

**Comment by jacko9000** [comment]
Google's increasing obsession with your location, combined with the recent onslaught of Android versions (in particular, I, J, K, L, M, N, and now O) has affected (often, ruined) many applications.  MAPS.ME has most definitely suffered.

I was told by Alexander Blinchikov that "the use of maps without the use of location is a fairly rare case".

It would appear that Google's obsession with your location is rubbing off on MAPS.ME.  Which would explain why the app it is panning back to that point.

I, too, would like the app to not follow my location, like in v6.0.7.  And then for it to not ask for location providers at all, like in v4.4.7.

**Comment by thany** [comment]
New version from Google Play. No fix.

Guys, why? Look at how long this issue has existed, look at how goddamn easy the fix is!!

**Comment by thany** [comment]
Yeah, just letting people know the absolute ridiculousness of this issue. Removing a perfectly good working feature, and then refusing to say "whoops, I guess ppl were using that, lemme just put it back in", I'm talking about the GOSHDARN* TRISTATE BUTTON I'VE BEEN ASKING BACK FOR, FOR THE LAST COUPLE OF MONTHS.

How hard can it be?!

* Insert a different cussword here. Use you imagnation.

**Comment by thany** [comment]
Is anyone going to fix this issue already??

**Comment by thany** [comment]
New update from the Play Store. No fix.

**Comment by thany** [comment]
Happened again. Just opened the app, and sweeeeeeeep, it flies back to my current location.

FFS guys, that's NOT where I'm working on stuff. Good UX is ubiquitous, and moves *out of the way* of the user. This kind of UX (also called crappy bullshit features) is intrusive, and inhibits productivity - every single time. The exact opposite of what one should expect.

**Comment by thany** [comment]
9 months in. No fix.

Guys... What. The. Hell.
How ducking hard is it really?

**Comment by MartinCologne** [comment]
I would also love an option in maps.me to temporarily switch off gps.

My scenario: I start the app and do a gps locating, to show my current location. Until here everything is fine. Then I start walking arround. I would love to hold the app open, to have a look to it from time to time. But when doing so, maps.me is killing my batterie while updating the gps location. At this point it would be perfect, to have any option to disable the gps temporarily.

For me to options could solve my problem:

An option, that a tapp on gps only does a single gps location and stopps afterwards.
An option, to switch off gps manually. For example by dopple tapping the gps button (my favorite).
Are the any plans to implement a feature like this?

Thanks!
Martin

**Comment by thany** [comment]
Devs: this issue is still not fixed with the latest version.

Please get of your lazy butts and fix the issue already! It's been OVER A WHOLE GODDAMN YEAR and it's a FIVE MINUTE FIX.

How hard can it be to get that tristate button back?!

**Comment by liondog** [comment]
Actually, some friends of mine that I recommended MAPS.ME pointed out excatly this behavior to be confusing. And they are by no means experts.

I'd also like to have an option that disables the current behavior. The maps starts moving all of the sudden and the place I inspected seconds before is gone.

**Comment by thany** [comment]
Yep, the only way is to deny the app access to your location. Then it's a useful app for mapping stuff, but useless for navigation (compare to oldschool navigation devices that don't have any notion of current position).

Then, when you allow it location access again, it becomes useful for navigation, but utter bollocks for mapping anywhere else than in your current location (because the map would jump right back to your current position at unpredictable points in time).

**Comment by bambamal** [comment]
I have to agree, to automatic pan to my location is very irritating. Finding a specific location on a map can take a while, and losing it because of this behaviour is very frustrating.

I dont see a reason for automatic panning to the location at all, why would i ever need this? If I want to see my location, it tap the location button and the map follows me. Tap it again, and it also turns the map. As soon as I swipe the location out of view, the app should never pan to my location, there is a specific button to do that, so i dont see who would find that useful.

I agree, that the app shouldnt ask me to turn on gps at startup. Makes no sense to me.

**Comment by thany** [comment]
Maps.me has their priorities in reverse order. In stead of adding useless online-only features that literally no one asked for, regression issues should be fixed with highest priority. The only type of issue with higher priority is a security issue.

I'd like to ask the Maps.me team: why is this issue not being addressed?

**Comment by nail-iumaguzin** [comment]
Oh god.
It's 2022 and the same annoying behaviour is still present.
Makes planning the trip much harder :(

**Comment by thany** [comment]
I'm switching to [Organic Maps](https://github.com/organicmaps/organicmaps). A fork of this project, with online and other bullshit removed, with a team behind it that actually listens to users and doesn't appear to have a hidden agenda.

Give MAPS.ME the finger. It was fun while it lasted, but you completely knackered yourselves, AFAIC.

**Comment by redmanmale** [comment]
I've switched more than year ago and happy since.
